export const initialForm = {
    partnerName: '',
    sex:'',
    login: '',
    password: '',
    startRegistration: '',
    endRegistration: '',
    course: '',
    email: '',
    name: '',
    socialName:'',
    cpf:'',
    birthDate:'',
    motherName:'',
    cep:'',
    street:'',
    number:'',
    complement:'',
    neighborhood: '',
    state:'',
    city:'',
    cellphone:'',
    checkRequisits: true|false,
    checkDeclaration: true|false
}

export const steps = [{step: '1', name:'Pré-requisitos'}, {step: '2', name:'Dados Pessoais'},{step: '3', name:'Validação de renda'},{step: '4', name:'Conclusão'}
]

export const sex = ['Feminino', 'Masculino']

export const listaStudant = [{
    name: 'Tadeu Brito Amaral',
    socialName: '',
    cpf: '458.254.184-54',
    birthDate: '1966-10-20',
    motherName: 'Nome da Mãe',
    cep: '45213-000',
    street: 'Rua Gema',
    number: '02',
    complement: '',
    neighborhood: 'Pq. Lima',
    state: 'SP',
    city: 'São Paulo',
    cellphone: '(11) 94521-1542',
    sex: 'Masculino',
    checkRequisits: 'T',
    checkDeclaration: 'T'
},{
    name: 'Mirian Oliveira Santos',
    socialName: 'Roberto Oliveira Santos',
    cpf: '445.248.521-85',
    birthDate: '1998-05-06',
    motherName: 'Roberta Franco Oliveira',
    cep: '05492-450',
    street: 'Rua Alba',
    number: '56',
    complement: 'apto 43',
    neighborhood: 'Vila Maracá',
    state: 'SP',
    city: 'São Carlos',
    cellphone: '(16) 94561-2515',
    sex: 'Masculino',
    checkRequisits: 'T',
    checkDeclaration: 'T'
}]

export const columns = [
    { id: 'name', label: 'Nome', minWidth: 170 },
    { id: 'socialName', label: 'Nome Social', minWidth: 100 },
    {
      id: 'cpf',
      label: 'CPF',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toLocaleString('pt-Br'),
    },
    {
      id: 'birthDate',
      label: 'Data de Nascimento',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toLocaleString('pt-Br'),
    },
    {
      id: 'motherName',
      label: 'Nome da Mãe',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'cep',
      label: 'CEP',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'street',
      label: 'Rua',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'number',
      label: 'Número',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'complement',
      label: 'Complemento',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'neighborhood',
      label: 'Bairro',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'state',
      label: 'Estado',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'city',
      label: 'Cidade',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'cellphone',
      label: 'Telefone',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'sex',
      label: 'Sexo',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'checkRequisits',
      label: 'De acordo Requisitos',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
    {
      id: 'checkDeclaration',
      label: 'Auto Declaração Renda',
      minWidth: 170,
      align: 'right',
      format: (value) => value.toFixed(2),
    },
  ];